### ISSUE TITLE
svelte-inspect v0.1.2  cause build error 

### ISSUE THREAD

**Issue by frantic0** [mimic-sussex/sema#295]
version 0.1.2 is causing this error (as reported in https://github.com/trbrc/svelte-inspect/issues/7)

```
[!] (plugin svelte) Error: Duplicate slot name "slot" in <Echo>
node_modules/svelte-inspect/inspect/formatters/SymbolFormatter.svelte
Error: Duplicate slot name "slot" in <Echo>
    at InlineComponentWrapper.set_slot (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:98:10)
    at new SlotTemplateWrapper (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/SlotTemplate.ts:60:15)
    at /Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:52
    at Array.map (<anonymous>)
    at new InlineComponentWrapper (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:39)
    at new FragmentWrapper (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/Fragment.ts:120:21)
    at new SlotTemplateWrapper (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/SlotTemplate.ts:65:19)
    at /Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:52
    at Array.map (<anonymous>)
    at new InlineComponentWrapper (/Users/francisco/Documents/dev/MIMIC/sema/node_modules/svelte/src/compiler/compile/render_dom/wrappers/InlineComponent/index.ts:87:39)
`````

**Comment by frantic0** [comment]
reverted to "svelte": "^3.23.2", for now
